env: 
  es6: true
  node: true

extends: eslint:recommended

parserOptions: 
  ecmaVersion: 2018

rules: 
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - warn
    - single
  semi:
    - error
    - never
  eqeqeq:
    - error
    - always
  no-console: off
  no-useless-escape: off